@args String entityNameShort, String entityNameLong,


package com.mindsignited.micloudrestbase.service;

import @entityNameLong;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.util.List;

/**
 * Auto Generated by Metashift
 * Originially Created by nicholaspadilla on 1/12/15.
 */
@@RepositoryRestResource(collectionResourceRel = "@entityNameShort.toLowerCase()s", path = "@entityNameShort.toLowerCase()s")
interface @(entityNameShort)Repository extends PagingAndSortingRepository<@(entityNameShort), Long> {

    @entityNameShort findByNameAndModel(@@Param("name") String name, @@Param("model") String model);

    List<@(entityNameShort)> findByModel(@@Param("model") String model);

}